const questionActionTypes = {
  FETCH_QUESTIONS_START: "FETCH_QUESTIONS_START",
  FETCH_QUESTIONS_SUCCESS: "FETCH_QUESTIONS_SUCCESS",
  FETCH_QUESTIONS_FAILURE: "FETCH_QUESTIONS_FAILURE",
  DOWNLOAD_INPUT_START: "DOWNLOAD_INPUT_START",
  DOWNLOAD_INPUT_SUCCESS: "DOWNLOAD_INPUT_SUCCESS",
  DOWNLOAD_INPUT_FAILURE: "DOWNLOAD_INPUT_FAILURE",
  CREATE_QUESTION_START: "CREATE_QUESTION_START",
  CREATE_QUESTION_SUCCESS: "CREATE_QUESTION_SUCCESS",
  CREATE_QUESTION_FAILURE: "CREATE_QUESTION_FAILURE",
  DELETE_QUESTION_START: "DELETE_QUESTION_START",
  DELETE_QUESTION_SUCCESS: "DELETE_QUESTION_SUCCESS",
  DELETE_QUESTION_FAILURE: "DELETE_QUESTION_FAILURE",
  EDIT_QUESTION_START: "EDIT_QUESTION_START",
  EDIT_QUESTION_SUCCESS: "EDIT_QUESTION_SUCCESS",
  EDIT_QUESTION_FAILURE: "EDIT_QUESTION_FAILURE",
  SET_ERRORS_NULL: "SET_ERRORS_NULL",
};

export const questionTypes = {
  MCQ: "mcq",
  MSQ: "msq",
  INPUT: "input",
  CODE: "code",
};
export default questionActionTypes;
