const answerActionTypes = {
  FETCH_QUESTION_ANSWERS_START: "FETCH_QUESTION_ANSWERS_START",
  FETCH_QUESTION_ANSWERS_SUCCESS: "FETCH_QUESTION_ANSWERS_SUCCESS",
  FETCH_QUESTION_ANSWERS_FAILURE: "FETCH_QUESTION_ANSWERS_FAILURE",
  UPDATE_SCORE_START: "UPDATE_SCORE_START",
  UPDATE_SCORE_SUCCESS: "UPDATE_SCORE_SUCCESS",
  UPDATE_SCORE_FAILURE: "UPDATE_SCORE_FAILURE",
  DOWNLOAD_CODE_START: "DOWNLOAD_CODE_START",
  DOWNLOAD_CODE_SUCCESS: "DOWNLOAD_CODE_SUCCESS",
  DOWNLOAD_CODE_FAILURE: "DOWNLOAD_CODE_FAILURE",
};

export default answerActionTypes;
