const challengeActionTypes = {
  UPDATE_STATUS: "UPDATE_STATUS",
  FETCH_CHALLENGE_START: "FETCH_CHALLENGE_START",
  FETCH_CHALLENGE_SUCCESS: "FETCH_CHALLENGE_SUCCESS",
  FETCH_CHALLENGE_FAILURE: "FETCH_CHALLENGE_FAILURE",
  EDIT_CHALLENGE_START: "EDIT_CHALLENGE_START",
  EDIT_CHALLENGE_SUCCESS: "EDIT_CHALLENGE_SUCCESS",
  EDIT_CHALLENGE_FAILURE: "EDIT_CHALLENGE_FAILURE",
};

export default challengeActionTypes;
