const leaderboardActionTypes = {
  FETCH_LEADERBOARD_START: "FETCH_LEADERBOARD_START",
  FETCH_LEADERBOARD_SUCCESS: "FETCH_LEADERBOARD_SUCCESS",
  FETCH_LEADERBOARD_FAILURE: "FETCH_LEADERBOARD_FAILURE",
};

export default leaderboardActionTypes;
